GET http://127.0.0.1:3001/subscribers

###

GET http://127.0.0.1:3001/subscribers/5eedf148ac82160b4c336ad8

###

POST http://127.0.0.1:3001/subscribers
Content-Type: application/json

{
    "name": "Wakoli Leon",
    "subscribedToChannel": "Techcamp Live"
}